[package]
name = "slash-formatter"
version = "2.2.1"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/slash-formatter"
homepage = "https://magiclen.org/slash-formatter"
keywords = ["slash", "url", "path", "string", "backslash"]
categories = ["value-formatting"]
description= "This crate provides functions to deal with slashes and backslashes in strings."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/slash-formatter", branch = "master" }
appveyor = { repository = "magiclen/slash-formatter", branch = "master", service = "github" }

[dependencies]
